ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS delivery_method VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS delivery_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS delivery_estimate VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS pickup_location TEXT NULL,
  ADD COLUMN IF NOT EXISTS account_holder_name VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(100) NULL;

ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS account_holder_name VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(100) NULL;
